name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: universal-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' || matrix.target == 'x86_64-unknown-linux-musl' }}
        run: sudo apt-get update &&  sudo apt-get install -y musl-tools

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qe_mac_apid
          build_tool: cargo
          archive: "qe_mac_apid-${{ matrix.target }}"
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
